### PR TITLE
Drops content-disposition header

### PR DESCRIPTION
**Pull request by jeantil**
The Content-Disposition header breaks the html import feature [1] which is
commonly used by web components frameworks such as polymer.
Therefore the `Ok.sendfile` helper is not appropriate for `GulpAssets` and
should be reserved to send over files to be downloaded
(whether forced downlading when disposition is attachment or providing a
filename for a preview when disposition is inline)

This commits drops `Ok.sendfile` in favor of `RangeResult.ofSource` which is the
method used by playframework's onw `Assets` controller.

[1] see https://www.w3.org/TR/html-imports/ and the following issues for the
rationale
 * https://bugs.chromium.org/p/chromium/issues/detail?id=439877
 * https://www.w3.org/Bugs/Public/show_bug.cgi?id=27550

### CODE REVIEW

**Comment by jeantil** [comment]
I upgraded to play 2.5.4 to have access to RangeResult which is used in the
current (2.5.10) `Assets` controller.

I considered upgrading as far as 2.5.10 where FileIO.fromFile is deprecated but
this would force users of the plugin to upgrade too. I thought 2.5.4 was a small
enough step to be worth it.

**Comment by almothafar** [comment]
@jeantil , This means we need more test for the plugin, but there is no way to handle both versions?
Also, there is no migration from 2.5.4 to 2.5.10, I know it is a bad idea to force people, but if so, you have to handle older versions like 2.4.x ? which is annoying, I think you would like to test the changes on those older versions.

And thanks for your contribution.

**Comment by jeantil** [comment]
@almothafar the pull request works fine from 2.5.4 to 2.5.10 and should work for any further 2.5.x release. I didn't want to use Iteratee/Enumeratee since they are going to be removed but it might be a better target. 

Regarding 2.4.x, the plugin already depends on 2.5.x.
Play doesn't guarantee any compatibility between minor versions (only for patch versions)
As an experiment, I tried building the code vs 2.4.8 and it doesn't compile. 

@mmizutani would you prefer a PR using  Iteratee/Enumeratee and staying on 2.5.0 ?

**Comment by jeantil** [comment]
I have pushed PR #23 which solves the content-disposition header issue with enumeratees and is compatible with 2.5.0+

**Pull request closed without merging**
